<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Otomatis_anni26-img</name>
   <tag></tag>
   <elementGuidId>e755b60e-f3f2-4ad4-bb78-b1174de73c1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#anni26-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='anni26-img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7bf784e1-1414-4943-878b-fbf413b519f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://asset.kompas.com/data/2023/09/20/kompascom/desktop/images/logo-kompascom-28.png</value>
      <webElementGuid>523b660f-72b9-43ae-832c-71a059bb819d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>28 Tahun Kompas.com, Jernih Melihat Dunia</value>
      <webElementGuid>7d6c957d-29dd-4f28-b72f-cdcfd6899909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anni26-img</value>
      <webElementGuid>0853d53f-abdd-4a3d-8543-f86dabd62340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anni26-img&quot;)</value>
      <webElementGuid>a6be0acd-9837-40b3-9226-ceded428017e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='anni26-img']</value>
      <webElementGuid>2f7bcd27-28fb-450c-813b-8c02b200945d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='28 Tahun Kompas.com, Jernih Melihat Dunia']</value>
      <webElementGuid>0e534076-59ba-4c7d-82d4-ab717f582371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>661442bd-8927-46b3-a494-d0a8e99d51d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://asset.kompas.com/data/2023/09/20/kompascom/desktop/images/logo-kompascom-28.png' and @alt = '28 Tahun Kompas.com, Jernih Melihat Dunia' and @id = 'anni26-img']</value>
      <webElementGuid>5c87ae56-3867-4810-b76e-383369ee00e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
