<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Second Div</name>
   <tag></tag>
   <elementGuidId>d80ba9c3-0984-4e58-8d5d-c36250000749</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5ff7c1b-740f-4387-8f40-e85386aceedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gs-title</value>
      <webElementGuid>7dd7b915-a1fb-40a1-96e4-1b8ac0d6a8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2020/01/22/15460191/refleksi-pemilu-2019-sebanyak-894-petugas-kpps-meninggal-dunia&amp;sa=U&amp;ved=2ahUKEwikxICD3IeEAxVojVYBHWXtC0MQFnoECAcQAg&amp;usg=AOvVaw11T7NtGnPqpWe5GLUQjH4k</value>
      <webElementGuid>31d94f60-96a3-4bcf-bdd7-97f46e655cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_parent</value>
      <webElementGuid>cde21f95-ff12-44f2-979b-a34d9c3aba2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>91a09d65-d98d-4d0a-91cf-d5223805001c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2020/01/22/15460191/refleksi-pemilu-2019-sebanyak-894-petugas-kpps-meninggal-dunia&amp;sa=U&amp;ved=2ahUKEwikxICD3IeEAxVojVYBHWXtC0MQFnoECAcQAg&amp;usg=AOvVaw11T7NtGnPqpWe5GLUQjH4k</value>
      <webElementGuid>d3b0cf73-f97a-44a8-a4f1-6e5da60abdd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctorig</name>
      <type>Main</type>
      <value>https://nasional.kompas.com/read/2020/01/22/15460191/refleksi-pemilu-2019-sebanyak-894-petugas-kpps-meninggal-dunia</value>
      <webElementGuid>34234cd0-b92e-42e1-9981-33215f85bd2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refleksi Pemilu 2019, Sebanyak 894 Petugas KPPS Meninggal Dunia</value>
      <webElementGuid>4d2f382c-c188-4e68-ad69-019b4ee8794a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;___gcse_0&quot;)/div[@class=&quot;gsc-control-cse gsc-control-cse-en&quot;]/div[@class=&quot;gsc-control-wrapper-cse&quot;]/div[@class=&quot;gsc-results-wrapper-nooverlay gsc-results-wrapper-visible&quot;]/div[@class=&quot;gsc-wrapper&quot;]/div[@class=&quot;gsc-resultsbox-visible&quot;]/div[@class=&quot;gsc-resultsRoot gsc-tabData gsc-tabdActive&quot;]/div[@class=&quot;gsc-results gsc-webResult&quot;]/div[@class=&quot;gsc-expansionArea&quot;]/div[@class=&quot;gsc-webResult gsc-result&quot;]/div[@class=&quot;gs-webResult gs-result&quot;]/div[@class=&quot;gsc-thumbnail-inside&quot;]/div[@class=&quot;gs-title&quot;]/a[@class=&quot;gs-title&quot;]</value>
      <webElementGuid>a908034d-0856-4ded-9b19-ab468dfcc4f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>ce90a29d-da13-4fd8-a8d3-b79cb93b1ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2020/01/22/15460191/refleksi-pemilu-2019-sebanyak-894-petugas-kpps-meninggal-dunia&amp;sa=U&amp;ved=2ahUKEwikxICD3IeEAxVojVYBHWXtC0MQFnoECAcQAg&amp;usg=AOvVaw11T7NtGnPqpWe5GLUQjH4k')]</value>
      <webElementGuid>a9e2718d-fd94-4c20-9688-d6dc2244e7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>174e8803-fa1f-4c1c-abc0-d1052b3f31c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2020/01/22/15460191/refleksi-pemilu-2019-sebanyak-894-petugas-kpps-meninggal-dunia&amp;sa=U&amp;ved=2ahUKEwikxICD3IeEAxVojVYBHWXtC0MQFnoECAcQAg&amp;usg=AOvVaw11T7NtGnPqpWe5GLUQjH4k' and (text() = 'Refleksi Pemilu 2019, Sebanyak 894 Petugas KPPS Meninggal Dunia' or . = 'Refleksi Pemilu 2019, Sebanyak 894 Petugas KPPS Meninggal Dunia')]</value>
      <webElementGuid>2b20d52d-249a-4409-aa0e-5e2fd802f3d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
