<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Second Berita Judul</name>
   <tag></tag>
   <elementGuidId>ac09bcdc-56b2-4bd6-a6de-9e6be3e38cc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.read__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c3cb1db3-335e-4be0-b6bf-77cf6f20f2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>read__title</value>
      <webElementGuid>a2ea70c0-14e0-40f3-be24-4d87df3267aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refleksi Pemilu 2019, Sebanyak 894 Petugas KPPS Meninggal Dunia</value>
      <webElementGuid>75433355-e0b6-42bf-a250-ae31b17db4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js csstransitions&quot;]/body[@class=&quot;theme--news page--read&quot;]/div[@class=&quot;wrap&quot;]/div[@class=&quot;container clearfix&quot;]/div[@class=&quot;row mt2 col-offset-fluid clearfix&quot;]/div[@class=&quot;col-bs10-10&quot;]/h1[@class=&quot;read__title&quot;]</value>
      <webElementGuid>20c369ee-4770-4b72-b01d-f7dfa66f9e39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>a4f69505-410c-4df5-86bb-2c363a72d50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Refleksi Pemilu 2019, Sebanyak 894 Petugas KPPS Meninggal Dunia' or . = 'Refleksi Pemilu 2019, Sebanyak 894 Petugas KPPS Meninggal Dunia')]</value>
      <webElementGuid>b9d3ea20-260e-4646-86f8-271d00428a27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
